### ISSUE TITLE
volgenmodel crash in pbs

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#1]
~/volgenmodel-nipype: nipypecli crash crash-20201218-151454-uqaste15-volsymm_on_short_01_-42580c6a-2103-4b31-b545-e94f7bdfce89.pklz 
 
File: /gpfs1/homes/uqaste15/volgenmodel-nipype/crash-20201218-151454-uqaste15-volsymm_on_short_01_-42580c6a-2103-4b31-b545-e94f7bdfce89.pklz
Node: workflow_temp_sahmri_template_try2PBSGraph24.volsymm_on_short_01_
Working directory: /gpfs1/scratch/30days/uqaste15/work/sahmri_template_try2/workflow_temp_sahmri_template_try2PBSGraph24/volsymm_on_short_01_

Node inputs:
args = <undefined>
clobber = True
config_file = /gpfs1/scratch/30days/uqaste15/work/sahmri_template_try2/workflow_temp_sahmri_template_try2PBSGraph24/write_conf_01_/fit_stage_01.conf
environ = {}
fit_linear = <undefined>
fit_nonlinear = True
input_file = /gpfs1/scratch/30days/uqaste15/work/sahmri_template_try2/workflow_temp_sahmri_template_try2PBSGraph24/resample_to_short_01_/sub-0001_acq-gre_E01_run-1_magnitude_rem_volcentre_norm_resample_bigaverage_reshape.mnc
input_grid_files = <undefined>
nofit = <undefined>
output_file = <undefined>
trans_file = <undefined>
verbose = <undefined>
x = True
y = <undefined>
z = <undefined>

Traceback: 
Traceback (most recent call last):
  File "/gpfs1/homes/uqaste15/volgenmodel-nipype/work_dir/sahmri_template_try2/workflow_temp_sahmri_template_try2PBSGraph24/batch/pyscript_20201218_150531_workflow_temp_sahmri_template_try2PBSGraph24_volsymm_on_short_01_.py", line 38, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
volsymm -clobber -config_file /gpfs1/scratch/30days/uqaste15/work/sahmri_template_try2/workflow_temp_sahmri_template_try2PBSGraph24/write_conf_01_/fit_stage_01.conf -nonlinear -x /gpfs1/scratch/30days/uqaste15/work/sahmri_template_try2/workflow_temp_sahmri_template_try2PBSGraph24/resample_to_short_01_/sub-0001_acq-gre_E01_run-1_magnitude_rem_volcentre_norm_resample_bigaverage_reshape.mnc sub-0001_acq-gre_E01_run-1_magnitude_rem_volcentre_norm_resample_bigaverage_reshape_vol_symm.xfm sub-0001_acq-gre_E01_run-1_magnitude_rem_volcentre_norm_resample_bigaverage_reshape_vol_symm.mnc
Standard output:
+++ generate flipped version +++
+++ [NLIN] xfm to self +++
Standard error:
Copying chunks:..........................................................................................................................................................................................Done.
Copying chunks:..........................................................................................................................................................................................Done.
couldn't create "/state/partition1/pbs/tmpdir/pbs.506789.awonmgr2/autocrop_22078/": No such file or directory
Can't create /state/partition1/pbs/tmpdir/pbs.506789.awonmgr2/autocrop_22078//sub-0001_acq-gre_E01_run-1_magnitude_rem_volcentre_norm_resample_bigaverage_reshape_bounds.tag: No such file or directory
Died at /opt/minc-1.9.17/bin/nlpfit line 404.
Died at /opt/minc-1.9.17/bin/volsymm line 213.
Return code: 2

**Comment by astewartau** [comment]
Solved - bindpath problem which needed /state.
