### ISSUE TITLE
DOC: MEGRE invalid BIDS naming

### ISSUE THREAD

**Issue by bpinsard** [QSMxT/QSMxT#131]
Thanks for that very nice pipeline that I intend to test and likely use.

I quickly noticed in the doc here: https://github.com/QSMxT/QSMxT/blob/bcbf6ca458c50b17a55e021e2191bdd252809a7e/docs/pages/4_using-qsmxt/1_data-preparation.md?plain=1#L143-L169  refers to invalid naming as `run-` entity is supposed to precede `echo-` one. I guess your software will work with the fixed version as your conversion is already implementing the correct naming https://github.com/QSMxT/QSMxT/blob/bcbf6ca458c50b17a55e021e2191bdd252809a7e/qsmxt/cli/dicom_convert.py#L502 

Cheers!

**Comment by astewartau** [comment]
Hi @bpinsard, thanks for your interest in using QSMxT and highlighting this problem! You are correct that there is an error in the documentation and I have corrected this just now in https://github.com/QSMxT/QSMxT/commit/0ff4b5979905cb922e3be5b242e8a233e17dbcf7. If you encounter any further issues or have any suggestions, please feel free to open further issues so I can get things working smoothly. :smile:
