### ISSUE TITLE
qsmxt usage typo

### ISSUE THREAD

**Issue by kerrinpine** [QSMxT/QSMxT#140]
[--add_bet [ADD_BET]]
             [--bet_fractional_intensity BET_FRACTIONAL_INTENSITY]
             [--export_dicoms] [--pbs PBS] [--slurm ACCOUNT_STRING PARITITON]
             [--n_procs N_PROCS] [--debug] [--list_premades] [--dry]

and

  --slurm ACCOUNT_STRING PARITITON
                        Run the pipeline via SLURM and use the argument as the
                        account string. (default: None)

Should be PARTITION no?

**Comment by astewartau** [comment]
Thanks so much for highlighting this! I fixed the `--help` and updated this in v7.2.2. The installation instructions are updated at https://qsmxt.github.io/QSMxT/installation.
