### ISSUE TITLE
overview diagram doesn't display ok in the dark theme of github

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#18]
![image](https://user-images.githubusercontent.com/4021595/116329932-bf285780-a80f-11eb-9404-c8ed08cf098a.png)

(maybe store as non-transparent png with white background :?)

**Comment by astewartau** [comment]
Fixed in https://github.com/QSMxT/QSMxT/commit/6ff68bd2ed9c23361cd3241451f22f62c98963ca
