### ISSUE TITLE
dicomToBids automation

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#2]
dicomToBids conversion could be a little more automated and possibly include dicomsort (which currently needs to be manually invoked)

**Comment by astewartau** [comment]
Added our own dicomsort script adapted from a Github gist (https://gist.github.com/alex-weston-13/4dae048b423f1b4cb9828734a4ec8b83) for our purposes. 

https://github.com/QSMxT/QSMxT/commit/42cd2dc095ea3a752d88dda92832221011004792
