### ISSUE TITLE
Small improvement to run_2_qsm.py

### ISSUE THREAD

**Issue by thomshaw92** [QSMxT/QSMxT#21]
Small bug or improvement suggestion: 
I ran my data through run_1_dicomToBids.py - but it didn't have a session identifier, because it wasn't necessary for me.
Data structure is output as sub-001 > anat > images.
When I run run_2_qsm.py, it can't find the data in the anat folder as it is looking for a ses-* folder.
can I set the --session_pattern option to '*' or something? Maybe could be documented in the options.

**Comment by astewartau** [comment]
We currently do not have an option to avoid the session identifier in run_2_qsm.py, though if you use run_0_dicomSort.py, it should automatically create a valid session folder (even if there is only one session for a subject), this should then cause the BIDS conversion to also use session folders, which should make it available for run_2_qsm.py. :)

**Comment by thomshaw92** [comment]
Makes sense!
I didn't run run_0 for this project as it was already done - it was an easy fix though in my script (in bash, sorry)...
```
if [[ -d ${sub}/anat && ! -d ${sub}/ses-01 ]] ; then
mkdir -p ${sub}/ses-01 && mv ${sub}/anat ${sub}/ses-01/
fi 
```
