### ISSUE TITLE
more robust dicom conversion

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#26]
The current dicom to bids conversion requires that we match certain patterns in the bidsmap.yaml and running 
```
python3 /opt/QSMxT/run_1_dicomToBids.py 00_dicom 01_bids
```

would it be helpful for users to run this command twice and manually sort phase and mag?
e.g.
```
python3 /opt/QSMxT/run_1_dicomToBids.py 00_dicom_magnitude 01_bids --type magnitude
python3 /opt/QSMxT/run_1_dicomToBids.py 00_dicom_phase 01_bids --type phase
```

**Comment by astewartau** [comment]
Moved away from bidscoin so we can interactively identify magnitude and phase series, or pattern match the 'series description' field using patterns specified using command-line arguments, e.g.
```
# run interactively
./run_1_dicomConvert.py 00_dicom 01_bids

# run non-interactively using custom patterns
./run_1_dicomConvert.py 00_dicom 01_bids --t2starw_series_patterns '*qsm*' '*gre*' --t1w_series_patterns '*T1*' --auto_yes
```
https://github.com/QSMxT/QSMxT/commit/29dfd25706fdd0eb8c7c370bcab28bc67e1c75f7
