### ISSUE TITLE
document starting from nii files in a custom structure

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#28]
Here's a quick example of what one of my BIDS folders looks like:

bids/ 
├── code
│   └── ...
├── ...
├── sub-m3137578
│   └── ses-1
│       ├── anat
│       │   ├── sub-m3137578_ses-1_acq-qsmE01_run-1_magnitude.json
│       │   ├── sub-m3137578_ses-1_acq-qsmE01_run-1_magnitude.nii.gz
│       │   ├── sub-m3137578_ses-1_acq-qsmE01_run-1_phase.json
│       │   ├── sub-m3137578_ses-1_acq-qsmE01_run-1_phase.nii.gz
│       │   ├── sub-m3137578_ses-1_acq-qsmE02_run-1_magnitude.json
│       │   ├── sub-m3137578_ses-1_acq-qsmE02_run-1_magnitude.nii.gz
│       │   ├── sub-m3137578_ses-1_acq-qsmE02_run-1_phase.json
│       │   ├── sub-m3137578_ses-1_acq-qsmE02_run-1_phase.nii.gz
│       │   ├── ...

The important part is that the directory structure must contain 'subject', 'session', and 'run' identifiers in the path to each file (see the highlighted/red text above). So for my example above, I would use:

./run_2_qsm.py \
    bids \
    out \
    --magnitude_pattern "{subject}/{session}/anat/sub*{run}*magnitude*nii*" \
    --phase_pattern "{subject}/{session}/anat/sub*{run}*phase*nii*" \
    --two_pass

**Comment by astewartau** [comment]
Solved in https://github.com/QSMxT/QSMxT/commit/b13fde8288f9f0dc7984edc90a9c1732092da6fc :smiley:
