### ISSUE TITLE
Insufficient memory

### ISSUE THREAD

**Issue by manonlevayer** [QSMxT/QSMxT#33]
Hi there! 

I'm a bit of an amateur when it comes to virtual platforms so I was wondering if you could help me fix this issue I came across while trying to run QSMxT on the demo data:

<img width="1280" alt="Screen Shot 2022-02-21 at 10 45 33 AM" src="https://user-images.githubusercontent.com/100100301/154869761-b9fb5883-08a2-4f33-bb47-2feab7be30d5.png">

Is the issue with my computer's memory or the virtual platform memory? How can I fix this issue?

Thank you so much in advance!

**Comment by stebo85** [comment]
Dear @manonlevayer - yes, you need to increase the amount of memory you provide to the docker container :) 

Which operating system are you running on? 

Here more information: https://neurodesk.github.io/docs/neurodesktop/troubleshooting/#i-got-an-error-message-x-killed

**Comment by manonlevayer** [comment]
Hi Steffen,

Thank you so much for the quick reply!! I am running the software on my MacBook (macOS Big Sur 11.6.4). I think the link you sent was meant for Windows users, does the same work for Mac? 

Thanks again,
Manon

**Comment by stebo85** [comment]
Yes, it will be similar for Mac: go to the docker settings and increase the
memory for docker. I don't have access to a Mac so if you post a print
screen here i can add it to he documentation.

**Comment by manonlevayer** [comment]
It works now! Thank you so much! Here is a screenshot of the Docker settings page

<img width="1270" alt="Screen Shot 2022-02-21 at 11 25 10 AM" src="https://user-images.githubusercontent.com/100100301/154871454-0d913812-2717-448f-b2ab-b4a2e0e99be3.png">

**Comment by stebo85** [comment]
Thanks to your help, this is now documented in the QSMxT Readme and in the Troubleshoot section: https://neurodesk.github.io/docs/neurodesktop/troubleshooting/
