### ISSUE TITLE
Please provide a complete set of dependencies for a bare-metal install

### ISSUE THREAD

**Issue by gdevenyi** [QSMxT/QSMxT#36]
The documentation does not provide a way to install this software without using containers.

Can you please provide the complete list of python packages and external binaries required to run it.

Thank you.

**Comment by stebo85** [comment]
Dear @gdevenyi,

Thank you so much for your feedback :)

Although we do not recommend installing the dependencies manually and we advocate the use of software containers for reproducibility and ease-of-use, you can install everything by hand. These are the dependencies required and this was tested in Ubuntu 18.04: 

You need:
- TGV-QSM running in miniconda 2
- fsl version=6.0.4
- ants version=2.3.4
- dcm2niix latest version from github
- miniconda version=4.7.12.1 with python 3.6 for nipype 1.6.0 pytorch 1.2.0 and torchvision 0.4.0 niflow-nipype1-workflows
- FastSurfer.git
- Bru2Nii v1.0.20180303
- julia-1.6.1 with ArgParse and MriResearchTools

Here is the detailed instruction that you could replicate: https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/qsmxtbase/build.sh and then on top https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/qsmxt/build.sh


Out of curiosity: Why do you want to install it bare metal and not use the software containers provided? 

Let me know if you run into any issues and I am more than happy to help.

Cheers
Steffen
