### ISSUE TITLE
DICOM sorting fails with certain dicom files -> should skip?

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#39]
Certain Dicom files seem to crash the dicom sorting:

python3 /opt/QSMxT/run_0_dicomSort.py SD 00_dicom
reading file list...
13120 dicom files found.
sorting dicoms in 00_dicom...
Identified subject: sd
Identified session: sd #1 20220406
Identified series: sub-sd/ses-1/27_aspire_qmetric_aspire_bipolar_qsm_0_8-iso_ne9
Identified series: sub-sd/ses-1/28_aspire_magcxsum_aspire_bipolar_qsm_0_8-iso_ne9
Identified series: sub-sd/ses-1/29_aspire_m_aspire_bipolar_qsm_0_8-iso_ne9
Identified series: sub-sd/ses-1/30_aspire_p_aspire_bipolar_qsm_0_8-iso_ne9
Identified series: sub-sd/ses-1/31_aspire_bipolar_qsm_0_8-iso_ne9
Identified series: sub-sd/ses-1/32_r2star_aspire_bipolar_qsm_0_8-iso_ne9
Identified series: sub-sd/ses-1/6_t1_mp2rage_0p5mm_7t_inv1
Identified series: sub-sd/ses-1/8_t1_mp2rage_0p5mm_7t_inv2
Identified series: sub-sd/ses-1/10_t1_mp2rage_0p5mm_7t_uni_images
Identified series: sub-sd/ses-1/22_t1_mp2rage_0p5mm_7t_inv1
Identified series: sub-sd/ses-1/24_t1_mp2rage_0p5mm_7t_inv2
Identified series: sub-sd/ses-1/26_t1_mp2rage_0p5mm_7t_uni_images
Identified series: sub-sd/ses-1/195_t1_mp2rage_0p5mm_7t_uni_images_den
Identified series: sub-sd/ses-1/20_cmrr_mbep2d_diff_b0_p-a
Identified series: sub-sd/ses-1/14_cmrr_mbep2d_diff_126dir
Identified series: sub-sd/ses-1/15_cmrr_mbep2d_diff_126dir_adc
Identified series: sub-sd/ses-1/16_cmrr_mbep2d_diff_126dir_tracew
Identified series: sub-sd/ses-1/17_cmrr_mbep2d_diff_126dir_fa
Identified series: sub-sd/ses-1/18_cmrr_mbep2d_diff_126dir_colfa
An exception occurred while decompressing SD/DWI/SD.MR.RESEARCH_21043_BRAIN_MECHANISM.0019.0001.2022.04.06.12.17.13.145050.105826837.IMA
Exception details: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset

Should we detect such a crash and continue sorting?

**Comment by astewartau** [comment]
Fixed in https://github.com/QSMxT/QSMxT/commit/77453e0c9d2740c4e6faa66e3a599328630d6144. These DICOM files are now sorted without decompressing them.
