### ISSUE TITLE
DICOM convert crashes on certain dicom files

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#40]
python3 /opt/QSMxT/run_1_dicomConvert.py 00_dicom 01_bids
Converting all DICOMs to nifti...
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/27_aspire_qmetric_aspire_bipolar_qsm_0_8-iso_ne9
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/28_aspire_magcxsum_aspire_bipolar_qsm_0_8-iso_ne9
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/29_aspire_m_aspire_bipolar_qsm_0_8-iso_ne9
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/30_aspire_p_aspire_bipolar_qsm_0_8-iso_ne9
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/31_aspire_bipolar_qsm_0_8-iso_ne9
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/32_r2star_aspire_bipolar_qsm_0_8-iso_ne9
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/6_t1_mp2rage_0p5mm_7t_inv1
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/8_t1_mp2rage_0p5mm_7t_inv2
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/10_t1_mp2rage_0p5mm_7t_uni_images
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/22_t1_mp2rage_0p5mm_7t_inv1
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/24_t1_mp2rage_0p5mm_7t_inv2
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/26_t1_mp2rage_0p5mm_7t_uni_images
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/195_t1_mp2rage_0p5mm_7t_uni_images_den
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/20_cmrr_mbep2d_diff_b0_p-a
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/14_cmrr_mbep2d_diff_126dir
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/15_cmrr_mbep2d_diff_126dir_adc
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/16_cmrr_mbep2d_diff_126dir_tracew
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/17_cmrr_mbep2d_diff_126dir_fa
dcm2niix -z n -o 01_bids/sub-sd/ses-1/extra_data 00_dicom/sub-sd/ses-1/18_cmrr_mbep2d_diff_126dir_colfa
Enumerating series names from JSON headers in '01_bids/.../extra_data' folders...
All series names identified: ['aspire_bipolar_qsm_0.8-iso_ne9', 'cmrr_mbep2d_diff_126dir', 'cmrr_mbep2d_diff_b0_p-a', 't1_mp2rage_0p5mm_7t']
Chosen t2starw patterns ['*t2starw*', '*qsm*'] matched with the following series: ['aspire_bipolar_qsm_0.8-iso_ne9']
No t1w series found matching pattern: *t1w*
1. aspire_bipolar_qsm_0.8-iso_ne9
2. cmrr_mbep2d_diff_126dir
3. cmrr_mbep2d_diff_b0_p-a
4. t1_mp2rage_0p5mm_7t
Identify t1w scans for automated segmentation (comma-separated numbers; enter nothing to ignore): 4
Identified matching t1w series: ['t1_mp2rage_0p5mm_7t']
Parsing JSON headers...
Traceback (most recent call last):
  File "/opt/QSMxT/run_1_dicomConvert.py", line 273, in <module>
    auto_yes=args.auto_yes
  File "/opt/QSMxT/run_1_dicomConvert.py", line 150, in convert_to_nifti
    details['part_type'] = 'phase' if 'P' in json_data['ImageType'] else 'magnitude'
KeyError: 'ImageType'

It happens with dicoms that don't have an 'ImageType' - any chance to ignore these files and keep going?

**Comment by astewartau** [comment]
Should be fixed in https://github.com/QSMxT/QSMxT/commit/27d8799ad741e72a32a0cd72016173fdb2f0512a

I have also realised that the protocol name is also an optional field in DICOM (as well as series description), so there might eventually be a need to automatically derive a name in such cases.

**Comment by stebo85** [comment]
Fantastic work :) Once there are enough new features we should probably do a new release?
