### ISSUE TITLE
Standard error: TGV-QSM

### ISSUE THREAD

**Issue by vinkirk** [QSMxT/QSMxT#41]
Hi,

I've used the QSMxT pipeline, specifically the _python3 /opt/QSMxT/run_2_qsm.py 01_bids 02_qsm_output_ , with good results when images are acquired coronally.  

However, when images are acquired transversally/axially, the following error message is given on the command line (please see below).  Any help would be appreciated.

Thanks,

Vinny

Running with 1 procesors
220415-21:55:42,432 nipype.utils WARNING:
	 A newer version (1.7.1) of nipy/nipype is available. You are using 1.6.0
220415-21:55:42,505 nipype.workflow INFO:
	 Workflow workflow_qsm settings: ['check', 'execution', 'logging', 'monitoring']
220415-21:55:42,517 nipype.workflow INFO:
	 Running in parallel.
220415-21:55:42,535 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:55:42,560 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.select_files" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/select_files".
220415-21:55:42,563 nipype.workflow INFO:
	 [Node] Running "select_files" ("interfaces.nipype_interface_selectfiles.SelectFiles")
220415-21:55:42,568 nipype.workflow INFO:
	 [Node] Finished "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.select_files".
220415-21:55:44,538 nipype.workflow INFO:
	 [Job 0] Completed (workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.select_files).
220415-21:55:44,541 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 3 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:55:44,560 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.get_stats" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/get_stats".
220415-21:55:44,562 nipype.workflow INFO:
	 [Node] Setting-up "_get_stats0" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/get_stats/mapflow/_get_stats0".
220415-21:55:44,564 nipype.workflow INFO:
	 [Node] Running "_get_stats0" ("nipype.interfaces.fsl.utils.ImageStats"), a CommandLine Interface with command:
fslstats /neurodesktop-storage/20220414/dicoms/01_bids/sub-20220414092742_t2_fl3d_tra_006/ses-1/anat/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase.nii.gz -R
220415-21:55:44,705 nipype.workflow INFO:
	 [Node] Finished "_get_stats0".
220415-21:55:44,706 nipype.workflow INFO:
	 [Node] Finished "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.get_stats".
220415-21:55:46,540 nipype.workflow INFO:
	 [Job 1] Completed (workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.get_stats).
220415-21:55:46,544 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 3 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:55:46,562 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.read_json" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/read_json".
220415-21:55:46,564 nipype.workflow INFO:
	 [Node] Setting-up "_read_json0" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/read_json/mapflow/_read_json0".
220415-21:55:46,565 nipype.workflow INFO:
	 [Node] Running "_read_json0" ("nipype.interfaces.utility.wrappers.Function")
220415-21:55:46,567 nipype.workflow INFO:
	 [Node] Finished "_read_json0".
220415-21:55:46,568 nipype.workflow INFO:
	 [Node] Finished "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.read_json".
220415-21:55:48,542 nipype.workflow INFO:
	 [Job 2] Completed (workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.read_json).
220415-21:55:48,545 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 2 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:55:48,563 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.magnitude_mask" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/magnitude_mask".
220415-21:55:48,566 nipype.workflow INFO:
	 [Node] Setting-up "_magnitude_mask0" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/magnitude_mask/mapflow/_magnitude_mask0".
220415-21:55:48,567 nipype.workflow INFO:
	 [Node] Running "_magnitude_mask0" ("nipype.interfaces.fsl.utils.ImageMaths"), a CommandLine Interface with command:
fslmaths /neurodesktop-storage/20220414/dicoms/01_bids/sub-20220414092742_t2_fl3d_tra_006/ses-1/anat/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude.nii.gz -thrp 30 -bin -ero -dilM /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/magnitude_mask/mapflow/_magnitude_mask0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask.nii.gz
220415-21:55:50,543 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 1 jobs ready. Free memory (GB): 13.74/13.94, Free processors: 0/1.
                     Currently running:
                       * workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.magnitude_mask
220415-21:55:53,361 nipype.workflow INFO:
	 [Node] Finished "_magnitude_mask0".
220415-21:55:53,361 nipype.workflow INFO:
	 [Node] Finished "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.magnitude_mask".
220415-21:55:54,549 nipype.workflow INFO:
	 [Job 3] Completed (workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.magnitude_mask).
220415-21:55:54,552 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 2 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:55:54,569 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.phase_scaled" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled".
220415-21:55:54,572 nipype.workflow INFO:
	 [Node] Setting-up "_phase_scaled0" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0".
220415-21:55:54,573 nipype.workflow INFO:
	 [Node] Running "_phase_scaled0" ("nipype.interfaces.fsl.utils.ImageMaths"), a CommandLine Interface with command:
fslmaths /neurodesktop-storage/20220414/dicoms/01_bids/sub-20220414092742_t2_fl3d_tra_006/ses-1/anat/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase.nii.gz -sub -4096.0000000000 -div 1303.4789839226 -sub 3.1415926536 /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled.nii.gz
220415-21:55:55,15 nipype.workflow INFO:
	 [Node] Finished "_phase_scaled0".
220415-21:55:55,16 nipype.workflow INFO:
	 [Node] Finished "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.phase_scaled".
220415-21:55:56,551 nipype.workflow INFO:
	 [Job 4] Completed (workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.phase_scaled).
220415-21:55:56,555 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:55:56,572 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.repeat_mask" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/repeat_mask".
220415-21:55:56,574 nipype.workflow INFO:
	 [Node] Setting-up "_repeat_mask0" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/repeat_mask/mapflow/_repeat_mask0".
220415-21:55:56,575 nipype.workflow INFO:
	 [Node] Running "_repeat_mask0" ("nipype.interfaces.utility.wrappers.Function")
220415-21:55:56,576 nipype.workflow INFO:
	 [Node] Finished "_repeat_mask0".
220415-21:55:56,577 nipype.workflow INFO:
	 [Node] Finished "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.repeat_mask".
220415-21:55:58,554 nipype.workflow INFO:
	 [Job 5] Completed (workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.repeat_mask).
220415-21:55:58,558 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 2 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:55:58,602 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.qsm" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/qsm".
220415-21:55:58,606 nipype.workflow INFO:
	 [Node] Setting-up "_qsm0" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/qsm/mapflow/_qsm0".
220415-21:55:58,608 nipype.workflow INFO:
	 [Node] Running "_qsm0" ("interfaces.nipype_interface_tgv_qsm.QSMappingInterface"), a CommandLine Interface with command:
tgv_qsm -t 0.038400 --alpha 0.0015 0.0005 -f 3.000000 -e 0  -i 1000 -m /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/magnitude_mask/mapflow/_magnitude_mask0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask.nii.gz -o _qsm -p /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled.nii.gz
220415-21:56:00,553 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 1 jobs ready. Free memory (GB): 13.74/13.94, Free processors: 0/1.
                     Currently running:
                       * workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.qsm
220415-21:56:01,714 nipype.workflow WARNING:
	 Storing result file without outputs
220415-21:56:01,715 nipype.workflow WARNING:
	 [Node] Error on "_qsm0" (/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/qsm/mapflow/_qsm0)
220415-21:56:01,716 nipype.workflow WARNING:
	 Storing result file without outputs
220415-21:56:01,717 nipype.workflow WARNING:
	 [Node] Error on "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.qsm" (/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/qsm)
220415-21:56:02,558 nipype.workflow ERROR:
	 Node qsm.a0 failed to run on host neurodesktop-20220222.
220415-21:56:02,559 nipype.workflow ERROR:
	 Saving crash info to /neurodesktop-storage/20220414/dicoms/crash-20220415-215602-user-qsm.a0-9d2068d0-9900-45b6-99ee-29ea48d5e346.pklz
Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__
    mp_context=mp_context,
TypeError: __init__() got an unexpected keyword argument 'initializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1386, in _run_interface
    self.config["execution"]["stop_on_first_crash"]
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1295, in _collate_results
    "Subnodes of node: %s failed:\n%s" % (self.name, "\n".join(msg))
Exception: Subnodes of node: qsm failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__
    mp_context=mp_context,

TypeError: __init__() got an unexpected keyword argument 'initializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 829, in _run_interface
    self.raise_exception(runtime)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 760, in raise_exception
    ).format(**runtime.dictcopy())

RuntimeError: Command:
tgv_qsm -t 0.038400 --alpha 0.0015 0.0005 -f 3.000000 -e 0  -i 1000 -m /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/magnitude_mask/mapflow/_magnitude_mask0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask.nii.gz -o _qsm -p /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled.nii.gz
Standard output:

Standard error:
 >>>>  TGV-QSM  <<<<< 
-----------------------------------------
loading files...
  phase: /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled.nii.gz
  mask:  /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/magnitude_mask/mapflow/_magnitude_mask0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask.nii.gz
  output: /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled_qsm_{number:03d}.nii.gz
Resampling phase data...
Resampling magnitude/mask data...
Orientation and/or resolution of mask and data does not match!
Return code: 1

220415-21:56:02,561 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:56:02,578 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.mask_filled" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/mask_filled".
220415-21:56:02,581 nipype.workflow INFO:
	 [Node] Setting-up "_mask_filled0" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/mask_filled/mapflow/_mask_filled0".
220415-21:56:02,582 nipype.workflow INFO:
	 [Node] Running "_mask_filled0" ("nipype.interfaces.fsl.utils.ImageMaths"), a CommandLine Interface with command:
fslmaths /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/magnitude_mask/mapflow/_magnitude_mask0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask.nii.gz -fillh /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/mask_filled/mapflow/_mask_filled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask_fillh.nii.gz
220415-21:56:03,59 nipype.workflow INFO:
	 [Node] Finished "_mask_filled0".
220415-21:56:03,60 nipype.workflow INFO:
	 [Node] Finished "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.mask_filled".
220415-21:56:04,559 nipype.workflow INFO:
	 [Job 7] Completed (workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.mask_filled).
220415-21:56:04,562 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:56:04,581 nipype.workflow INFO:
	 [Node] Setting-up "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.qsm_filledmask" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/qsm_filledmask".
220415-21:56:04,584 nipype.workflow INFO:
	 [Node] Setting-up "_qsm_filledmask0" in "/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/qsm_filledmask/mapflow/_qsm_filledmask0".
220415-21:56:04,585 nipype.workflow INFO:
	 [Node] Running "_qsm_filledmask0" ("interfaces.nipype_interface_tgv_qsm.QSMappingInterface"), a CommandLine Interface with command:
tgv_qsm -t 0.038400 --alpha 0.0015 0.0005 -f 3.000000 -e 0  -i 1000 -m /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/mask_filled/mapflow/_mask_filled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask_fillh.nii.gz -o _qsm-filled -p /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled.nii.gz
220415-21:56:06,559 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 0 jobs ready. Free memory (GB): 13.74/13.94, Free processors: 0/1.
                     Currently running:
                       * workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.qsm_filledmask
220415-21:56:07,641 nipype.workflow WARNING:
	 Storing result file without outputs
220415-21:56:07,642 nipype.workflow WARNING:
	 [Node] Error on "_qsm_filledmask0" (/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/qsm_filledmask/mapflow/_qsm_filledmask0)
220415-21:56:07,643 nipype.workflow WARNING:
	 Storing result file without outputs
220415-21:56:07,643 nipype.workflow WARNING:
	 [Node] Error on "workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.qsm_filledmask" (/neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/qsm_filledmask)
220415-21:56:08,564 nipype.workflow ERROR:
	 Node qsm_filledmask.a0 failed to run on host neurodesktop-20220222.
220415-21:56:08,565 nipype.workflow ERROR:
	 Saving crash info to /neurodesktop-storage/20220414/dicoms/crash-20220415-215608-user-qsm_filledmask.a0-7cd09919-936e-4920-9578-aa3656cea49d.pklz
Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__
    mp_context=mp_context,
TypeError: __init__() got an unexpected keyword argument 'initializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1386, in _run_interface
    self.config["execution"]["stop_on_first_crash"]
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1295, in _collate_results
    "Subnodes of node: %s failed:\n%s" % (self.name, "\n".join(msg))
Exception: Subnodes of node: qsm_filledmask failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__
    mp_context=mp_context,

TypeError: __init__() got an unexpected keyword argument 'initializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 829, in _run_interface
    self.raise_exception(runtime)

  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 760, in raise_exception
    ).format(**runtime.dictcopy())

RuntimeError: Command:
tgv_qsm -t 0.038400 --alpha 0.0015 0.0005 -f 3.000000 -e 0  -i 1000 -m /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/mask_filled/mapflow/_mask_filled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask_fillh.nii.gz -o _qsm-filled -p /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled.nii.gz
Standard output:

Standard error:
 >>>>  TGV-QSM  <<<<< 
-----------------------------------------
loading files...
  phase: /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled.nii.gz
  mask:  /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/mask_filled/mapflow/_mask_filled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-magnitude_mask_fillh.nii.gz
  output: /neurodesktop-storage/20220414/dicoms/02_qsm_output/workflow_qsm/sub-20220414092742_t2_fl3d_tra_006/ses-1/_run_run-1/phase_scaled/mapflow/_phase_scaled0/sub-20220414092742_t2_fl3d_tra_006_ses-1_run-1_part-phase_scaled_qsm-filled_{number:03d}.nii.gz
Resampling phase data...
Resampling magnitude/mask data...
Orientation and/or resolution of mask and data does not match!
Return code: 1

220415-21:56:08,567 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 13.94/13.94, Free processors: 1/1.
220415-21:56:10,563 nipype.workflow INFO:
	 ***********************************
220415-21:56:10,563 nipype.workflow ERROR:
	 could not run node: workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.qsm.a0
220415-21:56:10,563 nipype.workflow INFO:
	 crashfile: /neurodesktop-storage/20220414/dicoms/crash-20220415-215602-user-qsm.a0-9d2068d0-9900-45b6-99ee-29ea48d5e346.pklz
220415-21:56:10,563 nipype.workflow ERROR:
	 could not run node: workflow_qsm.sub-20220414092742_t2_fl3d_tra_006.ses-1.qsm_filledmask.a0
220415-21:56:10,564 nipype.workflow INFO:
	 crashfile: /neurodesktop-storage/20220414/dicoms/crash-20220415-215608-user-qsm_filledmask.a0-7cd09919-936e-4920-9578-aa3656cea49d.pklz
220415-21:56:10,564 nipype.workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/opt/QSMxT/run_2_qsm.py", line 680, in <module>
    'n_procs': args.n_procs
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/tools.py", line 98, in report_nodes_not_run
    ("Workflow did not execute cleanly. " "Check log for details")
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by stebo85** [comment]
Dear @vinkirk,

This is a bug in the resampling and should be fixed in version 1.1.10 of qsmxt - which version are you using?

@astewartau: You set no-resampling to default everywhere now as a work-around, right? It would still be good to fix the underlying bug in TGV-QSM to have resampling working properly :)

**Comment by vinkirk** [comment]
Hi @stebo85,

I am using version 1.1.9 of qsmxt on Neurodesktop.  I noticed recently that version 1.1.10 is no longer there.  I was using that version previously for my other datasets.

Thanks

**Comment by stebo85** [comment]
which version of neurodesk are you using?

**Comment by vinkirk** [comment]
I'm on Ubuntu so I used this command to run Neurodesk today:

sudo docker run \
  --shm-size=1gb -it --privileged --name neurodesktop \
  -v ~/neurodesktop-storage:/neurodesktop-storage \
  -e HOST_UID="$(id -u)" -e HOST_GID="$(id -g)"\
  -p 8080:8080 \
  -h neurodesktop-20220222 vnmd/neurodesktop:20220222

http://localhost:8080/#/?username=user&password=password

**Comment by stebo85** [comment]
@vinkirk ,

ok, that’s an old version :) The latest version can always be found on the website:


sudo docker run \
  --shm-size=1gb -it --privileged --name neurodesktop \
  -v ~/neurodesktop-storage:/neurodesktop-storage \
  -e HOST_UID="$(id -u)" -e HOST_GID="$(id -g)"\
  -p 8080:8080 \
  -h neurodesktop-20220329 vnmd/neurodesktop:20220329

This will have qsmxt 1.1.10

**Comment by vinkirk** [comment]
Thanks @stebo85!  I will try that and use qsmxt 1.1.10.

**Comment by stebo85** [comment]
If it doesn't work in 1.1.10 still then we need to look at this again and hopefully find a long-term fix for this issue (it's a bug in an underlying library that we don't control, so fixing it at the source is tricky)

**Comment by vinkirk** [comment]
This worked great thanks!  So, I guess the acquisition type (coronal vs transverse) doesn't matter for the pipeline.  Also, just wanted to double-check with you that the final output is found in the folder 'qsm_final'?

**Comment by stebo85** [comment]
ok, great to hear. All directions will work, but axial acquisition will give you most correct results. All other directions will give you a small quantification error.

**Comment by stebo85** [comment]
Yes, final output is in qsm_final directory

**Comment by astewartau** [comment]
> @astewartau: You set no-resampling to default everywhere now as a work-around, right? It would still be good to fix the underlying bug in TGV-QSM to have resampling working properly :)

Yes that is the current workaround because we ran into this issue often. I will look into doing this soon - an easier solution to modifying the source may be to resample using FSL as one of the first steps. From memory, it may be related to whether there are an odd or even number of slices.

**Comment by stebo85** [comment]
yes, agree! Resampling with FSL would be a better option than trying to fix it inside tgv_qsm - I add this to the issue
