### ISSUE TITLE
QSM reconstruction at sub-millimeter isotropic resolution

### ISSUE THREAD

**Issue by vinkirk** [QSMxT/QSMxT#45]
Hi,

The source Mag/Phase pairs that I use for QSM are at 0.8984mmx0.9000mmx0.8984mm, and hence the QSM output is also at the same voxel sizes. The command that I use through Neurodesk is..python3 /opt/QSMxT/run_2_qsm.py 01_bids 02_qsm_output --n_procs 1.

How can I get the QSM to be reconstructed at isotropic 0.5mm?

Thanks for your help,

Vinny

**Comment by stebo85** [comment]
Dear @vinkirk ,

if you want 0.5mm isotropic QSM you need to acquire the data at this resolution.

Upsampling the data afterwards would be possible, but doesn't do anything useful except increasing the file size :)

Kind regards
Steffen
