### ISSUE TITLE
Siemens swi 6-echo sequence

### ISSUE THREAD

**Issue by rosenph** [QSMxT/QSMxT#72]
### Discussed in https://github.com/QSMxT/QSMxT/discussions/71

<div type='discussions-op-text'>

<sup>Originally posted by **rosenph** September 14, 2022</sup>
Pleased to say that the 1-echo swi produced good QSM images. However, when I tried the 6-echo sequence on the Siemens, the QSM processing mysteriously and consistently failed after about 2-3 min. Attached is the screen grab from the Neurodesk output.
[error2.odt](https://github.com/QSMxT/QSMxT/files/9569174/error2.odt)
I'd be very grateful if you help us out.

</div>

**Comment by rosenph** [comment]
Thank you very much indeed for your help. I'll give it a go.

In the future we will want to transfer the QSM images to the hospital PACS, do you know of a reliable nifti to dicom converter?

**Comment by rosenph** [comment]
Dear Ashley,

I couldn't get your script to work.
I've attached the output in the terminal window.

Best regards,

Philip


‫בתאריך יום ב׳, 19 בספט׳ 2022 ב-23:30 מאת ‪Ashley‬‏ <‪
***@***.***‬‏>:‬

**Comment by rosenph** [comment]
Dear Ashley,

 I finally got the QSMxT processing to work with the 6-echo Siemens data.

All I had to do was to export the data (as a DICOM file system) with
Enhanced image conversion and not Interoperability. As simple as that!

Many thanks again for all your help.

Warm regards,

Philip Rosen.

‫בתאריך יום ג׳, 20 בספט׳ 2022 ב-11:24 מאת ‪Philip Rosen‬‏ <‪
***@***.***‬‏>:‬

**Comment by stebo85** [comment]
Dear @rosenph - great to hear it's all working now. Closing this issue.
