### ISSUE TITLE
Add option to specify ground truth for RMSE metrics in run_5_analysis.py

### ISSUE THREAD

**Issue by astewartau** [QSMxT/QSMxT#77]

**Comment by korbinian90** [comment]
I did some work on this in
https://github.com/korbinian90/QSMxT/tree/analysis_automation

**Comment by korbinian90** [comment]
https://github.com/QSMxT/QSMxT/issues/78#issuecomment-1318254702

**Comment by astewartau** [comment]
This feature is probably now best solved in QSM-CI.
