### ISSUE TITLE
Automatically quantify the volume of areas of ROIs missing from QSM in run_5_analysis.py

### ISSUE THREAD

**Issue by astewartau** [QSMxT/QSMxT#78]

**Comment by astewartau** [comment]
Not necessarily - since run_5_analysis takes `--segmentations` as input, any voxel equal to zero that is covered by a segmentation could be considered a missing region.

**Comment by korbinian90** [comment]
Here is a first attempt:
**https://github.com/korbinian90/QSMxT/tree/analysis_automation**

### Restructuring of the run_5_analysis.py file
- it can now be called directly from pytest, as only calling the main functions happens in `__main__`
- the default behaviour should be identical to before
### Added a comparison to ground truth by region
- `def diff_to_ground_truth_by_region(args, logger)`
- it contains a lot of duplicated code and might need a cleaner integration
### Added a first version of counting voxels that are cut from the brain
- `def num_voxels_cut_from_brain(qsm, seg)`
- only for qsm-challenge ground truth for now
### Script to run the the analysis on a range of settings
- https://github.com/korbinian90/QSMxT/blob/analysis_automation/tests/run_qsm_masking_experiment.py

=> These changes are not yet ready to be pulled in straight away, but might provide a good starting point (for discussion or implementation)

**Comment by astewartau** [comment]
Closing this for now as run_5_analysis.py no longer exists (analysis pipeline has been restructured). I created a [new issue](https://github.com/QSMxT/QSMxT/issues/109) for more advanced analyses using radiomics (possibly a student project idea).
