### ISSUE TITLE
CPU load at segmentation step

### ISSUE THREAD

**Issue by jhuguetn** [QSMxT/QSMxT#81]
I am trying to run QSMxT for a large set of cases in a server machine, thus parallelizing its execution. I have however found out that the pipeilne has an increase of CPU load at a given moment of its execution. Lasts no more than 5 min. but boosts CPU usage to 10 times the expected/preset CPU %.   
The event seems to be occurring at the segmentation step (`run_3_segment.py` script), perhaps related to FastSurfer. See below,
 
Full pipeline docker stats (setting nprocs to 4),
![image](https://user-images.githubusercontent.com/6368825/203330892-dd682f42-30f2-4035-a4f1-62702f6223e9.png)

Segmentation step docker stats (setting nprocs to 4),
![image](https://user-images.githubusercontent.com/6368825/203331085-933062fd-9552-46c3-8eeb-76857e43d538.png)

Constraining the CPU usage via --num_threads and/or --n_procs script flags does not seem to have an impact on this issue. Any ideas on how to control it?

**Comment by stebo85** [comment]
Dear @jhuguetn,

Thank you for finding this issue! It looks like a bug, but I am not sure why it's ignoring the thread count setting. 

@astewartau, do you have an idea why the thread setting might be ignored here:
https://github.com/QSMxT/QSMxT/blob/32c7fd66637e6fe5a21c259198548364b73094f9/run_3_segment.py#L106

Does it need to be passed into this?
https://github.com/QSMxT/QSMxT/blob/32c7fd66637e6fe5a21c259198548364b73094f9/interfaces/nipype_interface_fastsurfer.py#L26

**Comment by jhuguetn** [comment]
Thanks @stebo85 for looking into it. See below a snapshot of the process tree taken during the described issue, it seems to be indeed related to fastsurfer:
![image](https://user-images.githubusercontent.com/6368825/203600884-c8e258fd-c7ae-4bbb-9b32-77d16dd45810.png)

**Comment by astewartau** [comment]
I was able to reproduce this problem, and it indeed seems to be a limitation of FastSurfer, it seems to use all available CPUs, and we can only specify the number of threads used. I have opened an issue on their GitHub page asking if there is a way to limit the CPU usage to a specified number of CPUs.

**Comment by jhuguetn** [comment]
Dear @astewartau and @stebo85, 

Following the suggestion from https://github.com/Deep-MI/FastSurfer/issues/211 (thanks Ashley 🙏), I have tried including an environment variable `OMP_NUM_THREADS=4` in the container (directly, before running the Python script) and it apparently seem to work as expected. There are drawbacks however, now segmentation step takes aprox. 3 hours (from ~1.5 hours it did before) to run and memory usage is increased. Nevertheless, that's not critical for me as long as I keep CPU usage under control. See stats below,

![image](https://user-images.githubusercontent.com/6368825/205087363-df50cbed-f188-4569-b276-baa9db79d187.png)

Perhaps could be a good idea to just use the value of the input parameter `--n_procs` (when specified) to set 
 the env var. `OMP_NUM_THREADS` for FastSurfer/pytorch. What you think?

**Comment by astewartau** [comment]
Thanks again for identifying this problem and creating a pull request. I've integrated your fix and it seems to solve the problem. Let me know if you have any further issues.
